#!/bin/bash
set -x
set -e

mkdir -p build
cd build

cmake \
    -DCMAKE_INSTALL_PREFIX="${PREFIX}" \
    "${SRC_DIR}/src" \
    -DBUILD_SHARED_LIBS=ON \
    -DNCRYSTAL_NOTOUCH_CMAKE_BUILD_TYPE=ON \
    -DNCRYSTAL_MODIFY_RPATH=OFF \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DCMAKE_BUILD_TYPE=Release \
    -DNCRYSTAL_ENABLE_SETUPSH=OFF \
    -DNCRYSTAL_ENABLE_DATA=EMBED \
    -DNCRYSTAL_SKIP_PYMODINST=ON \
    -DPython3_EXECUTABLE="$PYTHON" \
    -DCMAKE_BUILD_PARALLEL_LEVEL=${CPU_COUNT:-1}
    ${CMAKE_ARGS}

cmake --build . --config Release
cmake --install .

#Note: There is no "make test" or "make ctest" functionality for NCrystal
#      yet. If it appears in the future, we should add it here.

TMPNCRYSTALLIBNAME=$(cat ./cfg_ncrystal_libname.txt)
cat <<EOF > ./ncrystal_pypkg/NCrystal/_nclibpath.py
#File autogenerated for working within a conda environment:
import pathlib
import os
_ = os.environ.get( 'CONDA_PREFIX', None )
if not _:
    raise RuntimeError('This installation of NCrystal was created for a conda environment but the CONDA_PREFIX variable is not set')
liblocation = pathlib.Path( _ ) / 'lib' / '${TMPNCRYSTALLIBNAME}'
if not liblocation.exists():
    raise RuntimeError('Could not find NCrystal library at expected location \$CONDA_PREFIX/lib/${TMPNCRYSTALLIBNAME}')
EOF
$PYTHON -m pip install ./ncrystal_pypkg/ --no-deps -vv
cd ..
