{% set version = "3.9.7" %}
{% set sha_value = "7b9ed5ae26d7971c1f4014b62c139631231450f3de32154626b38ea9c56f035f" %}
#NB get sha256 with: curl -sL <URL> | openssl sha256

package:
  name: ncrystal
  version: {{ version }}

source:
  url: https://github.com/mctools/ncrystal/archive/v{{ version }}.tar.gz
  sha256: {{ sha_value }}
  fn: ncrystal-src.tar.gz
  folder: src

build:
  number: 3
  skip: true  # [win]
  skip: true  # [py<38]

requirements:
  #todo: how do we add dependency on libdl.so? (or we must put -DNCRYSTAL_ENABLE_DYNLOAD=OFF).
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cmake
    - make  # [not win]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - numpy

test:
  requires:
    - python
    - numpy
    - cmake
  imports:
    - NCrystal
  commands:
    - ncrystal-config --help
    - ncrystal-config -s
    - nctool --version
    - nctool --help
    - nctool --test
    - ncrystal_endf2ncmat --help
    - ncrystal_hfg2ncmat --help
    - ncrystal_ncmat2cpp --help
    - ncrystal_ncmat2hkl --help
    - ncrystal_cif2ncmat --help
    - ncrystal_vdos2ncmat --help
    - ncrystal_verifyatompos --help
    - nctool --help
    - python3 -c 'import NCrystal; NCrystal.test()'
    - cmake --find-package -DNAME=NCrystal -DCOMPILER_ID=GNU -DLANGUAGE=CXX -DMODE=EXIST
about:
  home: https://github.com/mctools/ncrystal
  summary: Library for thermal neutron transport in crystals and other materials.
  description: |
    NCrystal is a library and toolkit for thermal neutron transport in crystals
    and other materials. It can be used standalone or as a backend for other
    Monte Carlo particle simulation frameworks.
  license: Apache-2.0
  license_family: Apache
  license_file: src/LICENSE
  doc_url: https://github.com/mctools/ncrystal/wiki
  dev_url: https://github.com/mctools/ncrystal

extra:
  recipe-maintainers:
    - tkittel
